apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ required ".Values.postgresql.external.host is required" .Values.postgresql.external.host | b64enc }}
  REDIS_URL: {{ required ".Values.redis.external.host is required" .Values.redis.external.host | b64enc }}
{{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_URL: http://{{ .Release.Name }}-master:9200
{{- end }}
{{- if .Values.push.firebaseCredentialsSecretKey }}
  FIREBASE_CREDENTIALS_JSON: {{ .Values.push.firebaseCredentialsSecretKey }}
{{- end }}
